### ISSUE TITLE
<input type="file"> should be required

### ISSUE THREAD

**Issue by jtotht** [poor-a/bead#1]
I got a `Some error happened during upload.` error message when I tried to send a submission without selecting the zip file. The `<input>` should have a `required` attribute so that the browser doesn’t let me submit the form in the first place (and I get a more meaningful error message). Probably an `accept=".zip,application/zip"` attribute (see [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept)), too, if the server doesn’t accept anything else anyway.

**Comment by poor-a** [comment]
Fixed in 0d0a2464aa50e06b69ea2a77ef9c9760af0f313b.
