### ISSUE TITLE
Unhelpful error message when trying to log in with email address

### ISSUE THREAD

**Issue by thebalu** [poor-a/bead#2]
When I accidentally try to login using 
`neptun@inf.elte.hu` as username instead of `neptun`, and enter the correct password, I get:
Some internal error happened, please contact the administrators.

Expected behavior:
- Incorrect username or password error
- Or log in successfully.

**Comment by poor-a** [comment]
Fixed in 1d08a76f6959a5ad28ae59642e8baaa96c4a78df.
