### ISSUE TITLE
Copy option for source code part in description of tasks

### ISSUE THREAD

**Issue by martinb214** [poor-a/bead#3]
**Given** a task in BE-AD.
**When** there is a source code part in the description.
**And** it should be used in the submission (e.g. it's a template for the task).
**Then** it would be helpful to have a copy option (e.g. a button) to copy only the source code part.

These code parts can be long (more than 100 lines) and Ctr + A selects everything on the page (toolbar, buttons, etc.).

**Comment by poor-a** [comment]
Implemented in 82be76aeb2513678ab9aa9bd20e8549b56610a9a.

**Comment by martinb214** [comment]
I just tried it and copying works fine. Thank you.
